# Generated by Django 6.0.2 on 2026-02-18 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_salon_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images', verbose_name='Image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Salon',
                'verbose_name_plural': 'Salons',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Price')),
                ('duration_time', models.IntegerField(verbose_name='Duration Time (min)')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.salon', verbose_name='Salon')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('status', models.CharField(blank=True, choices=[('c', 'Confirmed'), ('p', 'In Progress'), ('d', 'Done'), ('x', 'Canceled')], default='c', help_text='Booking status', max_length=2, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.salon', verbose_name='Salon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.service', verbose_name='Service')),
            ],
        ),
    ]
